export default {
  //root main
  ONBOARDING_NAVIGATION: "ONBOARDING_NAVIGATION",
  AUTH_NAVIGATION: "AUTH_NAVIGATION",
  BOTTOM_NAVIGATION: "BOTTOM_NAVIGATION",
  COMMON_NAVIGATION: "COMMON_NAVIGATION",

  //bottom container
  HOME_SCREEN: "HOME_SCREEN",
  SHORT_SCREEN: "SHORT_SCREEN",
  SUBSCRIPTION: "SUBSCRIPTION",
  LIBRARY: "LIBRARY",

  ACCOUNT_SCREEN: "ACCOUNT_SCREEN",
  WALLET_SCREEN: "WALLET_SCREEN",

  //onboarding container
  INTRO_SCREEN: "INTRO_SCREEN",

  //auth container
  IMPORT_WALLET: "IMPORT_WALLET",
  CREATE_NEW_WALLET: "CREATE_NEW_WALLET",
  SECURE_WALLET: "SECURE_WALLET",

  //common container
  VIDEO_DETAIL_SCREEN: "VIDEO_DETAIL_SCREEN",
  LISTING_VIDEO_SCREEN: "LISTING_VIDEO_SCREEN",
  SEARCH_SCREEN: "SEARCH_SCREEN",
};
